# Generated by Django 5.1.3 on 2024-11-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_category_slug_alter_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ingredients",
            field=models.TextField(blank=True, null=True, verbose_name="ingredients"),
        ),
    ]
